### ISSUE TITLE
golang不错，有前途

### ISSUE THREAD

**Issue by huazaili** [lingfan/sgjdt_golang_battle#1]
长见识了

**Comment by Gooooodman** [comment]
F:\Good\go\src>go run main.go
GAME Start
open C:/Users/ADMINI~1/AppData/Local/Temp/go-build156050886/command-line-arguments/_obj/exe/data/soldier.csv: The system cannot find the path specifie
d.
open C:/Users/ADMINI~1/AppData/Local/Temp/go-build156050886/command-line-arguments/_obj/exe/data/equipment.csv: The system cannot find the path specif
ied.
open C:/Users/ADMINI~1/AppData/Local/Temp/go-build156050886/command-line-arguments/_obj/exe/data/player.csv: The system cannot find the path specified
.
panic: runtime error: index out of range

goroutine 1 [running]:
_/F_/Good/go/src/sggj.(*Player).decipher(0xc082058120, 0x0, 0x0)
        F:/Good/go/src/sggj/player.go:43 +0x92a
_/F_/Good/go/src/sggj.NewGame(0xa, 0x14, 0x57)
        F:/Good/go/src/sggj/game.go:59 +0x19e
main.main()
        F:/Good/go/src/main.go:26 +0x172
exit status 2

**Comment by Gooooodman** [comment]
@lingfan  怎么回事？？？
